# Generated by Django 5.2.6 on 2025-10-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_profile_latitude_profile_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
